version: '3.8'

services:
  # 1. Ünite: Dispatcher
  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - book_service
      - borrowing_service
    networks:
      - app-network

  # 2. Ünite: Auth
  auth_service:
    build: ./login-service
    environment:
      - MONGO_URL=mongodb://auth_db:27017
    depends_on:
      - auth_db
    networks:
      - app-network

  # 3. Ünite: Book
  book_service:
    build: ./book_service
    environment:
      - MONGO_URL=mongodb://book_db:27017
    depends_on:
      - book_db
    networks:
      - app-network

  # 4. Ünite: Borrowing
  borrowing_service:
    build: ./borrowing_service
    environment:
      - MONGO_URL=mongodb://borrowing_db:27017
    depends_on:
      - borrowing_db
    networks:
      - app-network

  # Görsel Şov Ünitesi
  monitor_service:
    build: ./monitor_service
    ports:
      - "8081:8000"
    networks:
      - app-network

  # --- İZOLE NOSQL VERİTABANLARI (KALICI HAFIZA EKLENDİ) ---
  auth_db:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - auth_data:/data/db # Konteyner silinse de kullanıcılar silinmez

  book_db:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - book_data:/data/db # Kitap envanteri burada güvende

  borrowing_db:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - borrowing_data:/data/db

networks:
  app-network:
    driver: bridge

# --- KALICI VERİ ALANLARI TANIMI ---
volumes:
  auth_data:
  book_data:
  borrowing_data: